version: '3.8'

services:
  # Aplicação Next.js
  front-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Montar o diretório atual para desenvolvimento (opcional)
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - front-ai-network

  # Nginx como proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front-ai
    restart: unless-stopped
    networks:
      - front-ai-network

networks:
  front-ai-network:
    driver: bridge

volumes:
  node_modules:
  next_build:
